version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      
    working_directory: ~/myapp

    steps:
      - checkout
      
      # composer
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: composer-v1-{{ checksum "composer.json" }}

      # yarn
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn run build

      # a remote environment will be created, and our current primary container will be configured to use it, any docker-related commands we use will be safely executed in this new environment
      - setup_remote_docker

      # build image, push to dockerhub, and deploy
      - run:
          name: Build application Docker image
          command: |
            docker build -t $DOCKERHUB_REPO:$CIRCLE_BRANCH .
      - run:
          name: Push the Docker image to the registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKERHUB_REPO:$CIRCLE_BRANCH
      - run: 
          name: Deploy, ssh in, pull image, and run
          command: |
            cat deploy.sh | ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP